### ISSUE TITLE
Build fails with commit 22daff5

### ISSUE THREAD

**Issue by RomainL972** [j72016/android_kernel_samsung_universal7870#1]
Because of the changes made by the commit [22daff5c69f3948b1d73353e0a12ef0dd6ef6539](https://github.com/j72016/android_kernel_samsung_universal7870/commit/22daff5c69f3948b1d73353e0a12ef0dd6ef6539), the build fails with the following error message:
```
../../../../../../kernel/samsung/exynos7870/include/uapi/linux/v4l2-mediabus.h:55:2: error: redeclaration of enumerator 'V4L2_MBUS_FMT_XRGB8888_4X8_LE'
  V4L2_MBUS_FMT_XRGB8888_4X8_LE = 0x100e,
  ^
../../../../../../kernel/samsung/exynos7870/include/uapi/linux/v4l2-mediabus.h:53:2: note: previous definition of 'V4L2_MBUS_FMT_XRGB8888_4X8_LE' was here
  V4L2_MBUS_FMT_XRGB8888_4X8_LE = 0x1009,
  ^
../../../../../../kernel/samsung/exynos7870/include/uapi/linux/v4l2-mediabus.h:95:2: error: redeclaration of enumerator 'V4L2_MBUS_FMT_YUV8_1X24'
  V4L2_MBUS_FMT_YUV8_1X24 = 0x2014,
  ^
../../../../../../kernel/samsung/exynos7870/include/uapi/linux/v4l2-mediabus.h:79:2: note: previous definition of 'V4L2_MBUS_FMT_YUV8_1X24' was here
  V4L2_MBUS_FMT_YUV8_1X24 = 0x2013,
  ^

```

**Comment by yEsPaP** [comment]
> Because of the changes made by the commit [22daff5c69f3948b1d73353e0a12ef0dd6ef6539](https://github.com/j72016/android_kernel_samsung_universal7870/commit/22daff5c69f3948b1d73353e0a12ef0dd6ef6539), the build fails with the following error message:
> 
> ```
> ../../../../../../kernel/samsung/exynos7870/include/uapi/linux/v4l2-mediabus.h:55:2: error: redeclaration of enumerator 'V4L2_MBUS_FMT_XRGB8888_4X8_LE'
>   V4L2_MBUS_FMT_XRGB8888_4X8_LE = 0x100e,
>   ^
> ../../../../../../kernel/samsung/exynos7870/include/uapi/linux/v4l2-mediabus.h:53:2: note: previous definition of 'V4L2_MBUS_FMT_XRGB8888_4X8_LE' was here
>   V4L2_MBUS_FMT_XRGB8888_4X8_LE = 0x1009,
>   ^
> ../../../../../../kernel/samsung/exynos7870/include/uapi/linux/v4l2-mediabus.h:95:2: error: redeclaration of enumerator 'V4L2_MBUS_FMT_YUV8_1X24'
>   V4L2_MBUS_FMT_YUV8_1X24 = 0x2014,
>   ^
> ../../../../../../kernel/samsung/exynos7870/include/uapi/linux/v4l2-mediabus.h:79:2: note: previous definition of 'V4L2_MBUS_FMT_YUV8_1X24' was here
>   V4L2_MBUS_FMT_YUV8_1X24 = 0x2013,
>   ^
> ```

Yea ik :/. Btw never thought someone will compile my kernel
